### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by AntonOks** [raku-community-modules/OO-Monitors#20]
WARNING: Version mismatch for OO-Monitors ("https://github.com/jnthn/oo-monitors.git") found. META6.json has "1.1.1" but latest 'git tag' is "release-1.1.1"

CAn you please "change" the "git tag" to the "best practice" version showing tag, which in this case would be "v1.1.1". Thanks!

**Comment by 2colours** [comment]
Because it was easier to just close this issue without actually doing anything than solving it, or [another very legitimate 5 minute issue](https://github.com/jnthn/oo-monitors/issues/19).
